### ISSUE TITLE
Some other questions about rigid body simulation.

### ISSUE THREAD

**Issue by Xi-You** [PieKing1215/FallingSandSurvival#5]
In the question  #4 , it is mentioned that the rigid body shape is recalculated when the angle of the rigid body changes.

Look at this pickaxe.
![IMG_20200919_092635](https://user-images.githubusercontent.com/71115574/93845993-51460b80-fcd5-11ea-8e92-4c32400e2f32.jpg)
![IMG_20200919_092538](https://user-images.githubusercontent.com/71115574/93846050-83f00400-fcd5-11ea-886e-27d4f449535f.jpg)
![IMG_20200919_092616](https://user-images.githubusercontent.com/71115574/93846054-88b4b800-fcd5-11ea-96da-9700daf84056.jpg)

After the rigid body angle is changed, how is this shape transformation achieved?
I have not used those libraries and algorithms you mentioned.

**Comment by the0and** [comment]
The new shape is achieved through a series of matrix multiplications. As this process can be very complex, it's not necessary to hard code it, just let the graphics/physics libraries do the calculations for you. [This video](https://youtu.be/rHLEWRxRGiM) explains the math, and [this one](https://youtu.be/ih20l3pJoeU) is a demonstration of how to code it.

**Comment by the0and** [comment]
The new shape is achieved through a series of matrix multiplications. As this process can be very complex, it's not necessary to hard code it, just let the graphics/physics libraries do the calculations for you. [This video](https://youtu.be/XkY2DOUCWMU) explains the math, and [this one](https://youtu.be/ih20l3pJoeU) is a demonstration of how to code it.

**Comment by PieKing1215** [comment]
Thanks for answering @the0and; I'll add what I would have said as well:

It was unclear to me exactly what the original question was but assuming it was "How do you get the rigidbody to rotate due to physics?", the answer is that I used a library for the rigidbody physics engine (Box2D).

It would be an entire project of its own to make your own physics engine with similar scope to Box2D.

I'm not sure what kind of experience @Xi-You has, but I would highly recommend using a preexisting physics engine library unless they really know what they're doing (Though it doesn't hurt to know about the underlying concepts, and the videos @the0and linked are good).

**Comment by Xi-You** [comment]
Thanks for your reply.Maybe you have some misunderstandings about my question. This is also to blame for not having a specific overview of this question. I am very sorry.

Currently I am already using Box2d physics engine.

Thank you @the0and for providing the link.
